services:
  - type: web
    name: hwb-votes
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: hwb-votes-data
      mountPath: /opt/render/project/src/server
      sizeGB: 1
